export const ENEMIES = {
  drone: {
    name: 'Drone',
    health: 60,
    speed: 110,
    reward: 10,
    livesLost: 1,
    color: 0xff4444,
    size: 9,
  },
  mech: {
    name: 'Mech',
    health: 220,
    speed: 65,
    reward: 25,
    livesLost: 2,
    color: 0xff8800,
    size: 13,
  },
  speeder: {
    name: 'Speeder',
    health: 35,
    speed: 230,
    reward: 15,
    livesLost: 1,
    color: 0xffff00,
    size: 7,
  },
  tank: {
    name: 'Tank',
    health: 650,
    speed: 40,
    reward: 80,
    livesLost: 5,
    color: 0xff2200,
    size: 17,
  },
};
