export const TOWERS = {
  laser: {
    name: 'Laser',
    cost: 75,
    damage: 15,
    range: 150,
    fireRate: 500,
    projectileSpeed: 450,
    projectileColor: 0x00ffff,
    color: 0x00ffff,
    description: 'Fast, single target',
  },
  missile: {
    name: 'Missile',
    cost: 150,
    damage: 80,
    range: 200,
    fireRate: 2500,
    projectileSpeed: 220,
    projectileColor: 0xff6600,
    splashRadius: 55,
    color: 0xff6600,
    description: 'AOE blast damage',
  },
  emp: {
    name: 'EMP',
    cost: 100,
    damage: 8,
    range: 170,
    fireRate: 1800,
    projectileSpeed: 300,
    projectileColor: 0xaa00ff,
    slowFactor: 0.35,
    slowDuration: 2500,
    color: 0xaa00ff,
    description: 'Slows + damages',
  },
  plasma: {
    name: 'Plasma',
    cost: 200,
    damage: 125,
    range: 180,
    fireRate: 3500,
    projectileSpeed: 320,
    projectileColor: 0x00ff66,
    color: 0x00ff66,
    description: 'High damage burst',
  },
  minigun: {
    name: 'Minigun',
    cost: 200,
    damage: 8,
    range: 140,
    fireRate: 1200,
    projectileSpeed: 500,
    projectileColor: 0xffaa00,
    color: 0xffaa00,
    description: 'Rapid burst fire',
  },
  tesla: {
    name: 'Tesla',
    cost: 150,
    damage: 25,
    range: 130,
    fireRate: 1200,
    color: 0x44aaff,
    description: 'Chain lightning',
    chainCount: 4,
    chainRange: 80,
  },
  cryo: {
    name: 'Cryo',
    cost: 125,
    damage: 20,
    range: 160,
    fireRate: 2000,
    projectileSpeed: 260,
    projectileColor: 0x88eeff,
    freezeDuration: 2000,
    color: 0x88eeff,
    description: 'Freeze + shatter',
  },
  railgun: {
    name: 'Railgun',
    cost: 250,
    damage: 120,
    range: 220,
    fireRate: 2500,
    color: 0xffaa33,
    description: 'Pierces all in line',
  },
  nanite: {
    name: 'Nanite',
    cost: 175,
    damage: 6,
    range: 100,
    fireRate: 500,
    color: 0x44ff88,
    description: 'AoE damage over time',
  },
  artillery: {
    name: 'Artillery',
    cost: 300,
    damage: 200,
    range: 280,
    fireRate: 3000,
    projectileSpeed: 180,
    projectileColor: 0xff4444,
    splashRadius: 90,
    minRange: 150,
    color: 0xff4444,
    description: 'Huge AoE, long range',
  },
  supportRelay: {
    name: 'Relay',
    cost: 100,
    damage: 0,
    range: 120,
    fireRate: 1000,
    color: 0xeeeeff,
    description: '+25% fire rate nearby',
  },
};
